name: Add docs-reviewers request to the docs-content review board

# **What it does**: Adds PRs in github/github that requested a review from docs-reviewers to the docs-content review board
# **Why we have it**: To catch docs-reviewers requests in github/github
# **Who does it impact**: docs-content maintainers

on:
  workflow_dispatch:
  schedule:
    - cron: '50 */6 * * *'

permissions:
  contents: read

jobs:
  add-requests-to-board:
    name: Add requests to board
    if: ${{ github.repository == 'github/docs-internal' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo content
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Setup Node
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854
        with:
          node-version: 16.8.x
          cache: npm

      - name: Install dependencies
        run: npm install @octokit/graphql

      - name: Run script
        run: |
          node .github/actions-scripts/fr-add-docs-reviewers-requests.js
        env:
          TOKEN: ${{ secrets.DOCS_BOT_FR }}
          PROJECT_NUMBER: 2936
          ORGANIZATION: 'github'
          REPO: 'github'
          REVIEWER: 'docs-reviewers'
          # This is an educated guess of how many PRs are opened in a day on the github/github repo
          # If we are missing PRs, either increase this number or increase the frequency at which this script is run
          NUM_PRS: 100
