name: Lint JS

# **What it does**: Lints our JavaScript to ensure the code matches the specified code style.
# **Why we have it**: We want some level of consistency to our JavaScript.
# **Who does it impact**: Docs engineering, open-source engineering contributors.

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Setup node
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854
        with:
          node-version: 16.8.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npx eslint .
